# Group Variables for Kubernetes Setup

# Version of K3s to install
k3s_version: "v1.30.1+k3s1"

# Access token for the K3s cluster
# Replace with the actual value or export it as an environment variable before running the playbook
k3s_token: "K1087dd74c2b50b06d48bd556038cd052699a4afccd4a9022cd9f684c8e23234412::server:caa961879044aa4f88edb3fe9613000c"

#Path to the kubeconfig file
kubeconfig_path: ~/.kube/config

# Definition of cluster nodes
master_node: raspberry-daniel
worker_nodes:
  - k3s-worker-1

# Pod definitions to be deployed
kubernetes_pods:
  - name: web-test
    image: nginx
    replicas: 4
    namespace: default

# Service definitions to expose the pods
kubernetes_services:
  - name: web-test
    type: NodePort
    port: 80
    targetPort: 80
    namespace: default
