- name: Update APT package index
  apt:
    update_cache: yes

- name: Upgrade all installed packages
  apt:
    upgrade: dist

- name: Install useful packages
  apt:
    name: "{{ packages_to_install }}"
    state: present

- name: Create user
  user:
    name: "{{ user_name }}"
    groups: sudo
    shell: /bin/bash
    state: present

- name: Set hostname
  hostname:
    name: "{{ new_hostname }}"
  notify: Reboot device

- name: Update /etc/hosts with new hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ new_hostname }}"

- name: Show loaded Variables
  debug:
    var: packages_to_install
